name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby 2.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Bundler Install
        run: |
          gem install bundler --no-document
          bundle install --jobs 4 --retry 3
      - name: Run RuboCop
        run: bundle exec rubocop
